name: test-reports

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test reports
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          # Add your xlwings license key as XLWINGS_LICENSE_KEY under
          # Settings > Secrets > Actions > New Repository secret
          XLWINGS_LICENSE_KEY: ${{ secrets.XLWINGS_LICENSE_KEY }}
        run: pytest -vv
